### ISSUE TITLE
Make new release with slimrbOptions

### ISSUE THREAD

**Issue by jonricaurte** [Scrimmage/karma-slim-preprocessor#4]
Can you make a new release so we can use the slimrbOptions in master instead of forking and referencing our fork?

Thanks!

**Comment by ratbeard** [comment]
Thanks for reminding me, just released v1.0.0 :tada:  :exclamation:

**Comment by rosstroha** [comment]
@ratbeard npm still sees the version as 0.0.6

**Comment by ratbeard** [comment]
Sorry bout that.  Just ran `npm publish`.  Should be good now 👊
